[package]
name = "radix-engine-constants"
version = "0.10.0"
edition = "2021"

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false
