[package]
name = "radix-engine"
version = "0.10.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine-constants = { path = "../radix-engine-constants" }
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false }
radix-engine-stores = { path = "../radix-engine-stores", default-features = false }
native-sdk = { path = "../native-sdk", default-features = false }
transaction = { path = "../transaction", default-features = false }
utils = { path = "../utils", default-features = false }
colored = { version = "2.0.0", default-features = false }
hex = { version = "0.4.3", default-features = false }
bitflags = { version = "1.3" }
lru = { version = "0.8.1", default-features = false, optional = true}
moka = { version = "0.9.4", features = ["sync"], default-features = false, optional = true }
strum = { version = "0.24", default-features = false, features = ["derive"] }
perfcnt = { version = "0.8.0", optional = true }
radix-engine-utils = { path = "../radix-engine-utils", optional = true, features = ["resource_tracker"] }
resources-tracker-macro = { path = "../radix-engine-utils/resources-tracker-macro" }

# WASM de-/serialization
parity-wasm = { version = "0.42.2" }

# WASM validation
wasmi-validation =  { version = "0.4.1" }

# WASM instrumentation
wasm-instrument = { version = "0.1.0" }

# WASM execution
# - Wasmi is a WASM interpreter that supports WebAssembly MVP
# - Wasmer is a WASM engine with multiple backends: `singlepass` (linear time), `LLVM` and `cranelift`

# FIXME: fetch wasmi from a forker repo until issue https://github.com/paritytech/wasmi/issues/631 is not fixed
wasmi = {  git = "https://github.com/radixdlt/wasmi.git", branch = "v0.23.0_store_clone"  }
wasmer = { version = "2.2.1", optional = true }
wasmer-compiler-singlepass = { version = "2.2.1", optional = true }

serde_json = { version = "1.0.81", optional = true, default-features = false }

[dev-dependencies]
wabt = { version = "0.10.0" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "native-sdk/std", "wasmi/std", "transaction/std", "radix-engine-interface/std", "radix-engine-stores/std", "utils/std", "moka", "serde_json?/std"]
alloc = ["sbor/alloc", "native-sdk/alloc", "transaction/alloc", "radix-engine-interface/alloc", "radix-engine-stores/alloc", "utils/alloc", "lru/hashbrown", "serde_json?/alloc"]

# Enables heap memory and CPU cycles resource tracing - available only for Linux OS on x86 arch.
# Requires CAP_PERFMON capability for the process (sudo setcap cap_perfmon=eip <exec_file>).
cpu_ram_metrics = ["std", "dep:perfcnt"] 

# Use `wasmer` as WASM engine, otherwise `wasmi`
wasmer = ["dep:wasmer", "dep:wasmer-compiler-singlepass"]

# Use moka for caching
moka = ["dep:moka"]

resource_tracker = ["dep:radix-engine-utils", "resources-tracker-macro/resource_tracker"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false
