[package]
name = "scrypto"
version = "0.10.0"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", default-features = false }
num-traits = { version = "0.2.15", default-features = false }
num-bigint = { version = "0.4.3", default-features = false }
bech32 = { version = "0.9.0", default-features = false }
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
radix-engine-derive = { path = "../radix-engine-derive", default-features = false }
sbor = { path = "../sbor", default-features = false }
scrypto-schema = { path = "../scrypto-schema", default-features = false }
scrypto-derive = { path = "../scrypto-derive", default-features = false }
utils = { path = "../utils", default-features = false }
paste = { version = "1.0.7"}
serde = { version = "1.0.144", default-features = false, optional = true }
strum = { version = "0.24", default-features = false, features = ["derive"] }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["hex/std", "sbor/std", "scrypto-schema/std", "scrypto-derive/std", "strum/std", "radix-engine-interface/std", "radix-engine-derive/std", "utils/std"]
alloc = ["hex/alloc", "sbor/alloc", "scrypto-schema/alloc", "scrypto-derive/alloc", "radix-engine-interface/alloc", "radix-engine-derive/alloc", "utils/alloc"]

# Turn on this feature to enable tracing.
trace = ["scrypto-derive/trace"]

# Disable schema gen in the output WASM.
no-schema = ["scrypto-derive/no-schema"]

[lib]
bench = false
