[package]
name = "resources-tracker-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
bench = false

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
radix-engine-utils = { path = "../../radix-engine-utils" }

[features]
default = []
resource_tracker = []

