[package]
name = "sbor-derive"
version = "0.10.0"
edition = "2021"

[lib]
proc-macro = true
bench = false

[dependencies]
proc-macro2 = { version = "1.0.38" }
sbor-derive-common = { path = "../sbor-derive-common" }

[features]
trace = ["sbor-derive-common/trace"]
